"Filed out from Dolphin Smallalk"!

AbstractB subclass: #ConcreteB
	instanceVariableNames: 'b'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ConcreteB guid: (GUID fromString: '{e57bf062-b41d-4043-947f-795c9fde9b3b}')!
ConcreteB comment: ''!
!ConcreteB categoriesForClass!Unclassified! !
!ConcreteB class methodsFor!

reStoreDefinition

	^super reStoreDefinition
		define: #b as: String;
		yourself! !
!ConcreteB class categoriesForMethods!
reStoreDefinition!public! !
!

