"Filed out from Dolphin Smalltalk"!

SSWDBStaticField subclass: #SSWDBControlField
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWDBControlField guid: (GUID fromString: '{9fce8e0c-f431-4b8b-9f80-df2d27959fa6}')!
SSWDBControlField comment: ''!
!SSWDBControlField categoriesForClass!Unclassified! !
!SSWDBControlField methodsFor!

populateObject: anObject with: aValue

	"Usually a no-op for control fields"! !
!SSWDBControlField categoriesForMethods!
populateObject:with:!actions!private! !
!

