"Filed out from Dolphin Smalltalk 7"!

SSWDBStringWithInfo subclass: #SSWDBVariableStringWithInfo
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWDBVariableStringWithInfo guid: (GUID fromString: '{f9276a85-4893-11d5-b1df-0010a70883e2}')!
SSWDBVariableStringWithInfo comment: 'ReStore
©2019 John Aspinall
https://github.com/rko281/ReStore'!
!SSWDBVariableStringWithInfo categoriesForClass!Unclassified! !
