"Filed out from Dolphin Smallalk"!

SSWDBStaticCollectionSpec subclass: #SSWDBStaticIdentitySetSpec
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWDBStaticIdentitySetSpec guid: (GUID fromString: '{445ff037-3306-4d55-8b8a-2ea6cad65153}')!
SSWDBStaticIdentitySetSpec comment: ''!
!SSWDBStaticIdentitySetSpec categoriesForClass!Unclassified! !
!SSWDBStaticIdentitySetSpec methodsFor!

shouldCompareChangesByEquality

	"I represent an IdentitySet"

	^false! !
!SSWDBStaticIdentitySetSpec categoriesForMethods!
shouldCompareChangesByEquality!change detection!private!testing! !
!

