"Filed out from Dolphin Smalltalk 7"!

SSWDBStringWithInfo subclass: #SSWDBByteArrayWithInfo
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWDBByteArrayWithInfo guid: (GUID fromString: '{75de4604-7020-45e5-a19c-9ec88a917cb5}')!
SSWDBByteArrayWithInfo comment: ''!
!SSWDBByteArrayWithInfo categoriesForClass!Unclassified! !
!SSWDBByteArrayWithInfo methodsFor!

infoClass

	^ByteArray! !
!SSWDBByteArrayWithInfo categoriesFor: #infoClass!public! !

