"Filed out from Dolphin Smalltalk"!

SSWDBDateAndTimeWithResolution subclass: #SSWDBDateAndTimeTimezoneAware
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SSWDBDateAndTimeTimezoneAware guid: (GUID fromString: '{d58ca285-76f0-40df-ae99-2a71dd571564}')!

SSWDBDateAndTimeTimezoneAware comment: ''!

!SSWDBDateAndTimeTimezoneAware categoriesForClass!Unclassified! !

