"Filed out from Dolphin Smalltalk 7"!

SSWDBStringWithInfo subclass: #SSWDBFixedStringWithInfo
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWDBFixedStringWithInfo guid: (GUID fromString: '{f9276a84-4893-11d5-b1df-0010a70883e2}')!
SSWDBFixedStringWithInfo comment: 'ReStore
©2019 John Aspinall
https://github.com/rko281/ReStore'!
!SSWDBFixedStringWithInfo categoriesForClass!Unclassified! !
