"Filed out from Dolphin Smalltalk 7"!

SSWDBStaticField subclass: #SSWDBNonParameterizedStaticField
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWDBNonParameterizedStaticField guid: (GUID fromString: '{6e06adb3-0662-48dc-8bae-2ff56760cbdb}')!
SSWDBNonParameterizedStaticField comment: 'ReStore
©2019 John Aspinall
https://github.com/rko281/ReStore'!
!SSWDBNonParameterizedStaticField categoriesForClass!Unclassified! !
!SSWDBNonParameterizedStaticField methodsFor!

canBeParameterized

	^false! !
!SSWDBNonParameterizedStaticField categoriesFor: #canBeParameterized!public!testing! !

