"Filed out from Dolphin Smalltalk"!

SSWDBControlField subclass: #SSWDBNonParameterizedControlField
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWDBNonParameterizedControlField guid: (GUID fromString: '{11052234-5ac0-4dc5-8e20-5b5e49b93fba}')!
SSWDBNonParameterizedControlField comment: ''!
!SSWDBNonParameterizedControlField categoriesForClass!Unclassified! !
!SSWDBNonParameterizedControlField methodsFor!

canBeParameterized

	^false! !
!SSWDBNonParameterizedControlField categoriesForMethods!
canBeParameterized!public!testing! !
!

