"Filed out from Dolphin Smalltalk"!

MySQLCommandFetch subclass: #SSWMySQLCommandFetch
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SSWMySQLCommandFetch guid: (GUID fromString: '{ee41c904-fb88-4177-a265-0a58cc246fba}')!

SSWMySQLCommandFetch comment: ''!

!SSWMySQLCommandFetch categoriesForClass!MySQL-Core-Command! !

!SSWMySQLCommandFetch methodsFor!

rowClass
				   
	^SSWMySQLRow! !

!SSWMySQLCommandFetch categoriesForMethods!
rowClass!accessing!public! !
!

