"Filed out from Dolphin Smalltalk"!

MySQLCommandQuery subclass: #SSWMySQLCommandQuery
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SSWMySQLCommandQuery guid: (GUID fromString: '{c6d3e501-5b78-4729-9a32-2d91e87020dc}')!

SSWMySQLCommandQuery comment: ''!

!SSWMySQLCommandQuery categoriesForClass!MySQL-Core-Command! !

!SSWMySQLCommandQuery methodsFor!

resultSetClass

	^SSWMySQLResultSet! !

!SSWMySQLCommandQuery categoriesForMethods!
resultSetClass!accessing!public! !
!

