"Filed out from Dolphin Smalltalk"!

MySQLCommandExecute subclass: #SSWMySQLCommandExecute
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SSWMySQLCommandExecute guid: (GUID fromString: '{e94881ea-668b-4846-8b81-861de8acea25}')!

SSWMySQLCommandExecute comment: ''!

!SSWMySQLCommandExecute categoriesForClass!MySQL-Core-Command! !

!SSWMySQLCommandExecute methodsFor!

resultSetClass

	^SSWMySQLResultSet!

rowClass
				   
	^SSWMySQLRow! !

!SSWMySQLCommandExecute categoriesForMethods!
resultSetClass!accessing!public! !
rowClass!accessing!public! !
!

