"Filed out from Dolphin Smalltalk"!

SSWMySQLDialect subclass: #SSWMariaDBDialect
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

SSWMariaDBDialect guid: (GUID fromString: '{693b8b35-d384-435c-bf41-3b4cbfb75003}')!

SSWMariaDBDialect comment: ''!

!SSWMariaDBDialect categoriesForClass!Unclassified! !

!SSWMariaDBDialect class methodsFor!

dbmsName

	^'MariaDB'! !

!SSWMariaDBDialect class categoriesForMethods!
dbmsName!constants!public! !
!

