"Filed out from Dolphin Smalltalk 7"!

SSWReStoreMultiValueCacheDictionaryTest subclass: #SSWReStoreOwnedMultiValueCacheDictionaryTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWReStoreOwnedMultiValueCacheDictionaryTest guid: (GUID fromString: '{b60d118c-fde5-481f-a782-01df4fd789b4}')!
SSWReStoreOwnedMultiValueCacheDictionaryTest comment: 'ReStore
©2020 John Aspinall
https://github.com/rko281/ReStore'!
!SSWReStoreOwnedMultiValueCacheDictionaryTest categoriesForClass!Unclassified! !
!SSWReStoreOwnedMultiValueCacheDictionaryTest methodsFor!

componentDefinition

	^Dictionary of: #key -> (OrderedCollection of: GenericOwnedTest dependent) owner: #owner! !
!SSWReStoreOwnedMultiValueCacheDictionaryTest categoriesFor: #componentDefinition!public! !

