"Filed out from Dolphin Smalltalk 7"!

SSWReStoreMultiValueCacheDictionaryTest subclass: #SSWReStoreMultiValueOwnedCacheDictionaryTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWReStoreMultiValueOwnedCacheDictionaryTest guid: (GUID fromString: '{b60d118c-fde5-481f-a782-01df4fd789b4}')!
SSWReStoreMultiValueOwnedCacheDictionaryTest comment: ''!
!SSWReStoreMultiValueOwnedCacheDictionaryTest categoriesForClass!Unclassified! !
!SSWReStoreMultiValueOwnedCacheDictionaryTest methodsFor!

componentDefinition

	^Dictionary of: #key -> (OrderedCollection of: GenericOwnedTest) owner: #owner! !
!SSWReStoreMultiValueOwnedCacheDictionaryTest categoriesFor: #componentDefinition!public! !

