"Filed out from Dolphin Smalltalk 7"!

SSWReStoreRelatedCacheDictionaryTest subclass: #SSWReStoreRelatedOwnedCacheDictionaryTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWReStoreRelatedOwnedCacheDictionaryTest guid: (GUID fromString: '{119e2157-321e-4e72-aae3-db0d53fb5aab}')!
SSWReStoreRelatedOwnedCacheDictionaryTest comment: 'ReStore
©2020 John Aspinall
https://github.com/rko281/ReStore'!
!SSWReStoreRelatedOwnedCacheDictionaryTest categoriesForClass!Unclassified! !
!SSWReStoreRelatedOwnedCacheDictionaryTest methodsFor!

componentDefinition

	^(Dictionary of: #key -> GenericOwnedTest related owner: #owner)! !
!SSWReStoreRelatedOwnedCacheDictionaryTest categoriesFor: #componentDefinition!accessing!public! !

