"Filed out from Dolphin Smalltalk 7"!

SSWReStoreCacheDictionaryTest subclass: #SSWReStoreOwnedCacheDictionaryTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWReStoreOwnedCacheDictionaryTest guid: (GUID fromString: '{2b0516fa-7b14-4f74-bd1b-e472ed4bff85}')!
SSWReStoreOwnedCacheDictionaryTest comment: 'ReStore
©2020 John Aspinall
https://github.com/rko281/ReStore'!
!SSWReStoreOwnedCacheDictionaryTest categoriesForClass!Unclassified! !
!SSWReStoreOwnedCacheDictionaryTest methodsFor!

componentDefinition

	^Dictionary of: #key -> GenericOwnedTest dependent owner: #owner! !
!SSWReStoreOwnedCacheDictionaryTest categoriesFor: #componentDefinition!public! !

