"Filed out from Dolphin Smalltalk 7"!

SSWReStoreNonRelatedCacheDictionaryTest subclass: #SSWReStoreNonRelatedOwnedCacheDictionaryTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWReStoreNonRelatedOwnedCacheDictionaryTest guid: (GUID fromString: '{9223b89c-c9f5-4335-9bd1-f54944107718}')!
SSWReStoreNonRelatedOwnedCacheDictionaryTest comment: 'ReStore
©2020 John Aspinall
https://github.com/rko281/ReStore'!
!SSWReStoreNonRelatedOwnedCacheDictionaryTest categoriesForClass!Unclassified! !
!SSWReStoreNonRelatedOwnedCacheDictionaryTest methodsFor!

componentDefinition

	^(Dictionary of: #key -> GenericOwnedTest owner: #owner)! !
!SSWReStoreNonRelatedOwnedCacheDictionaryTest categoriesFor: #componentDefinition!accessing!public! !

