"Filed out from Dolphin Smallalk"!

SSWReStoreUUIDTest subclass: #SSWReStoreUUIDSubTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWReStoreUUIDSubTest guid: (GUID fromString: '{917b317c-7889-4350-bad0-51e5f0f80d1f}')!
SSWReStoreUUIDSubTest comment: ''!
!SSWReStoreUUIDSubTest categoriesForClass!Unclassified! !
!SSWReStoreUUIDSubTest methodsFor!

addClassesTo: aReStore

	aReStore addClassWithSubclasses: UUIDOwnedTest!

testClass

	^UUIDOwnedSubTest! !
!SSWReStoreUUIDSubTest categoriesForMethods!
addClassesTo:!public!running! !
testClass!public!running! !
!

