"Filed out from Dolphin Smalltalk"!

SSWSQLiteDialect subclass: #SSWSQLiteNativeDialect
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWSQLiteNativeDialect guid: (GUID fromString: '{af9af1e6-6118-40ec-9684-a76f555792b1}')!
SSWSQLiteNativeDialect comment: ''!
!SSWSQLiteNativeDialect categoriesForClass!Unclassified! !
!SSWSQLiteNativeDialect methodsFor!

defaultDateTimeResolution

	^6! !
!SSWSQLiteNativeDialect categoriesForMethods!
defaultDateTimeResolution!constants!public! !
!

