"Filed out from Dolphin Smallalk"!

OwnedTest subclass: #UUIDOwnedTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
UUIDOwnedTest guid: (GUID fromString: '{2c239978-d2d1-412f-9836-830c8344ecbb}')!
UUIDOwnedTest comment: ''!
!UUIDOwnedTest categoriesForClass!Unclassified! !
!UUIDOwnedTest class methodsFor!

reStoreIDClass

	^GUID!

shouldInheritPersistency

	^false! !
!UUIDOwnedTest class categoriesForMethods!
reStoreIDClass!public! !
shouldInheritPersistency!public! !
!

